---
- name: create users
  hosts: all
  vars_files:
    - vars/users

  tasks:
  - name: create users
    user:
     name: "{{ item.value.username }}"
     comment: "{{ item.value.comment }}"
     home: "{{ item.value.homedir }}"
     shell: "{{ item.value.shell }}"
     password: "{{ item.value.password | password_hash('sha512') }}"
     update_password: on_create
       
    with_dict: "{{ users }}"
