--- 
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  
- include_tasks: "setup-{{ ansible_os_family }}.yml"

- name: Ensure Apache has selected state and enabled on boot.
  service:
    name: "{{ apache_service }}"
    state: "{{ apache_state }}"
    enabled: "{{ apache_enabled }}"
    
- name: Create index.html
  template:
    src: "{{ apache_index_html_template }}"
    dest: "{{ apache_index_html }}"
  notify: restart apache
    

