---

- name: Allow full read/write access SELinux
  seboolean:
    name: ftpd_full_access
    state: yes
    persistent: yes
  tags: vsftpd
  when:
   - ansible_os_family == 'RedHat'
   
- name: Allow anon read/write access SELinux
  seboolean:
    name: ftpd_anon_write
    state: yes
    persistent: yes
  tags: vsftpd
  when:
   - ansible_os_family == 'RedHat'
